server:
  version: 1.0
  port: 8080

# Management
management:
  server:
    port: 8081

swagger:
  alternateUrl: "/api-docs"

db:
  exe: "/usr/bin/pg_dump"
  host: localhost
  port: 5432
  username: postgres
  password: password
  name: myDbName
  tables: table1, table2, table3

auth:
  # Connection retries in case of connection failure
  connection:

    # Max number of retries
    maxRetries: 5

    # Initial timeoutMs before the first retry. In milliseconds.
    initialBackoff: 15000

    # Multiplier that defines value of consequent timeouts before the next retry.
    # E.g. TIMEOUT(n) = TIMEOUT(n-1) * MULTIPLIER
    multiplier: 2.0

---
spring.profiles: dev

management:
  server:
    port: -1

auth:
  server:
    prefix: "collab"
    suffix: "upload"

---

spring:
  profiles: prod

auth:
  server:
    url: "http://localhost:8000/check_token/"
    clientId: "clientId"
    clientSecret: "clientSecret"
    enableStrictSSL: false
    enableHttpLogging: false
    prefix: "collab"
    suffix: "upload"

